### PR TITLE
Monoid and Semigroup instances for Template

### PR DESCRIPTION
**Pull request by trskop**

### CODE REVIEW

**Review by tibbe — APPROVED** [review]

**Comment by tibbe** [comment]
Could you give me your Hackage username so I can add you there as well?

**Comment by trskop** [comment]
It's `PeterTrsko`. Thanks!

**Comment by tibbe** [comment]
Added on Hackage.

**Comment by creichert** [comment]
@trskop @tibbe 	thank you so much for this. I pick up this package for small tasks in a pinch so I don't have to reinvent this every time.

**Pull request merged**
